// examples/vue-app/src/ui/RbIdentity.vue
<template>

<div class="rb-component rb-identity">
    <table>
        <tr><th>Component:</th><td>&lt;{{name}}&gt; #{{instance}}</td></tr>
        <tr><th>Package:</th><td>{{package}}@{{version}}</td></tr>
        <tr><th>Description:</th><td>Displays REST response for <code>/{{service || "NO-SERVICE"}}/identity</code></td></tr>
    </table>
</div>

</template><!- ==================== --> <script>

var axios = require("axios");
var name = "rb-identity";

export default {
    name: name,
    props: {
        service: {
            type: String,
            required: true,
        }
    },
    data() {
        console.log("RbIdentity vue data", this.service);
        return {
            name: name,
            package: "tbd",
            version: "tbd",
        }
    },
    computed: {
        instance() {
            return 432;
        }
    },
    mounted() {
        console.log("rb-identity beforeMount", this.service);
        this.$store.commit("addRestBundle", { name: this.service });
        axios.get("/" + this.service + "/identity")
            .then((res) => {
                var json = res.data;
                this.package = json.package || this.package;
                this.version = json.version || this.version;
            })
            .catch((err) => {
                console.log("err", err);
                this.package = err.message;
                this.version = err.message;
            });
    }
}

</script><!-- ================= --><style>

.rb-component {
    border: 1pt solid #888;
    background-color: #eee;
    margin: 0.1em;
}

</style>

// src/ui/app/rb-identity.component.ts
import { Component, ElementRef, OnChanges, OnInit, AfterViewInit, Input } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/toPromise';

@Component({
    selector: 'rb-identity',
    template: `
        <div class="rb-component rb-identity">
            <table>
                <tr><th>Component:</th><td>&lt;{{name}}&gt; #{{instance}}</td></tr>
                <tr><th>Package:</th><td>{{package}}@{{version}}</td></tr>
                <tr><th>Description:</th><td>Displays REST response for <code>/{{service || "NO-SERVICE"}}/identity</code></td></tr>
            </table>
        </div>
        `,
    styles: [`
        .rb-component {
            padding: 5pt;
            border-radius: 5px;
            border: 1pt solid #555;
            background-color: #eee;
            font-family: Verdata,sans-serif;
            }
        th {
            text-align: left;
        }
    `],
    providers: [ ],
})
export class RbIdentity implements AfterViewInit { 
    static instances = 0;
    @Input() service :string;

    instance = ++RbIdentity.instances;
    name = 'rb-identity'; 
    package = "(package unknown)";
    version = "(version unknown)";
    constructor(eref:ElementRef, public http:Http) {
        this.service = eref.nativeElement.getAttribute("service");
    }
    ngAfterViewInit() {
        var that = this;
        this.service && this.http.get("/" + that.service + "/identity")
            .toPromise()
            .then((res) => {
                var json = res.json();
                that.package = json.package || that.package;
                that.version = json.version || that.version;
            })
            .catch((err:any) => console.log("err", err));
    }
}
