// examples/vue-app/src/ui/App.vue
<template>
  <div id="app">
    <h1> <img src="./assets/logo.png" height="25px"> {{msg}}</h1>
    This application currently has the following RestBundles:
    <rb-identity service="greeting">(Loading rb-identity)..</rb-identity>
    <rb-identity service="aloha">(Loading rb-identity)..</rb-identity>
    <template v-for="s of $store.getters.restBundles">
        restBunde:{{s}}
        <rb-identity :service="s">(Loading rb-identity)..</rb-identity>
    </template>

  </div>

</template> <!-- ====================================== --> <script>

import RbIdentity from './RbIdentity.vue';

export default {
    name: 'app',
    data () {
        return {
            msg: 'App.vue component'
        }
    },
    computed: {
        restBundles() {
            return this.$store.getters.restBundles;
        },
    },
    components: {
        RbIdentity
    },
}

</script><!-- ====================================== --> <style>

#app {
    border: 1pt solid black;
    border-radius: 5px;
    background-color: #eee;
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #2c3e50;
    margin-top: 60px;
    padding: 5px;
}

h1, h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>

// examples/demo/app/app.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'demo-ui',
    styles: [`
        .demo-ui {
            padding: 5pt;
            border-radius: 5px;
            border: 1pt solid #5a5;
            background-color: #efe;
            font-family: Arial, Helvetica, sans-serif;
        }
        h1 {
            color: #369;
            font-size: 125%;
        }
    `],// styles
    template: `
        <div class="demo-ui">
            <h1>Demo application root component {{seconds}}</h1>
            This application component includes the library component &lt;rest-bundle-identity&gt;:
            <div *ngFor='let srv of ["greeting","aloha"]'>
                {{srv}}
                <rest-bundle-identity [service]="srv">
                    Loading RestBundleIdentityComponent content here ...
                </rest-bundle-identity>
            </div>
            two:
            <rest-bundle-identity service="aloha">
                Loading RestBundleIdentityComponent content here ...
            </rest-bundle-identity>
        </div>
    `,// template
})
export class AppComponent  { 
    name = 'demo-ui'; 
    seconds = 0;
    constructor() {
        setInterval(() => (this.seconds++), 1000);
    }
}
